/** 工具参数的运行时描述。TypeScript 不保留参数类型和注释，因此 action 参数需显式声明。 */
export interface ToolParameterOptions {
  name: string;
  type: string;
  description: string;
  required?: boolean;
  default?: unknown;
}

export class ToolParameter {
  name: string;
  type: string;
  description: string;
  required: boolean;
  default: unknown;

  constructor({
    name,
    type,
    description,
    required = true,
    default: defaultValue = null,
  }: ToolParameterOptions) {
    this.name = name;
    this.type = type;
    this.description = description;
    this.required = required;
    this.default = defaultValue;
  }
}

interface ToolActionMetadata {
  name?: string;
  description?: string;
  parameters: ToolParameterOptions[];
}

const toolActions = new WeakMap<Function, ToolActionMetadata>();

/** 标记实例方法为可展开的 action；TypeScript 会擦除类型和注释，参数需按方法入参顺序显式声明。 */
export function toolAction(
  name?: string,
  description?: string,
  parameters: ToolParameterOptions[] = [],
): MethodDecorator {
  return (_target, _propertyKey, descriptor) => {
    if (typeof descriptor?.value === "function") {
      toolActions.set(descriptor.value, {
        name,
        description,
        parameters: parameters.map((parameter) => ({ ...parameter })),
      });
    }
  };
}

export interface OpenAIToolSchema {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: {
      type: "object";
      properties: Record<string, { type: string; description: string; items?: { type: string } }>;
      required: string[];
    };
  };
}

export type ToolResult = string | Record<string, unknown>;

export abstract class Tool {
  constructor(
    public name: string,
    public description: string,
    public expandable = false,
  ) {}

  abstract run(parameters: Record<string, unknown>): ToolResult | Promise<ToolResult>;

  abstract getParameters(): ToolParameter[];

  getExpandedTools(): Tool[] | null {
    if (!this.expandable) return null;

    const tools: Tool[] = [];
    const seenNames = new Set<string>();

    for (
      let prototype: object | null = Object.getPrototypeOf(this);
      prototype && prototype !== Tool.prototype;
      prototype = Object.getPrototypeOf(prototype)
    ) {
      for (const methodName of Object.getOwnPropertyNames(prototype).sort()) {
        if (methodName === "constructor" || seenNames.has(methodName)) continue;
        seenNames.add(methodName);

        const method = Object.getOwnPropertyDescriptor(prototype, methodName)?.value;
        if (typeof method !== "function") continue;

        const metadata = toolActions.get(method);
        if (!metadata) continue;

        tools.push(
          new AutoGeneratedTool(
            this,
            method,
            metadata.name,
            metadata.description,
            metadata.parameters,
          ),
        );
      }
    }

    return tools.length > 0 ? tools : null;
  }

  validateParameters(parameters: Record<string, unknown>): boolean {
    return this.getParameters()
      .filter((parameter) => parameter.required)
      .every((parameter) => Object.hasOwn(parameters, parameter.name));
  }

  toDict(): { name: string; description: string; parameters: ToolParameter[] } {
    return {
      name: this.name,
      description: this.description,
      parameters: this.getParameters().map(
        ({ name, type, description, required, default: defaultValue }) =>
          new ToolParameter({ name, type, description, required, default: defaultValue }),
      ),
    };
  }

  toOpenAISchema(): OpenAIToolSchema {
    const properties: OpenAIToolSchema["function"]["parameters"]["properties"] = {};
    const required: string[] = [];

    for (const parameter of this.getParameters()) {
      let description = parameter.description;
      if (parameter.default !== null && parameter.default !== undefined) {
        const defaultValue =
          typeof parameter.default === "string"
            ? parameter.default
            : JSON.stringify(parameter.default);
        description += ` (默认: ${defaultValue ?? ""})`;
      }

      properties[parameter.name] = {
        type: parameter.type,
        description,
        ...(parameter.type === "array" ? { items: { type: "string" } } : {}),
      };

      if (parameter.required) required.push(parameter.name);
    }

    return {
      type: "function",
      function: {
        name: this.name,
        description: this.description,
        parameters: { type: "object", properties, required },
      },
    };
  }

  toString(): string {
    return `Tool(name=${this.name})`;
  }
}

export class AutoGeneratedTool extends Tool {
  private readonly parameters: ToolParameter[];

  constructor(
    public readonly parent: Tool,
    public readonly method: Function,
    name?: string,
    description?: string,
    parameters: ToolParameterOptions[] = [],
  ) {
    const methodName = method.name;
    super(
      name ?? `${parent.name}_${methodName.replace(/^_+/, "")}`,
      description ?? `执行 ${methodName}`,
    );
    this.parameters = parameters.map((parameter) => new ToolParameter(parameter));
  }

  getParameters(): ToolParameter[] {
    return this.parameters;
  }

  run(parameters: Record<string, unknown>): ToolResult | Promise<ToolResult> {
    const parameterNames = new Set(this.parameters.map((parameter) => parameter.name));
    const unexpected = Object.keys(parameters).filter((name) => !parameterNames.has(name));
    if (unexpected.length > 0) {
      throw new TypeError(`Unexpected parameter(s): ${unexpected.join(", ")}`);
    }

    const missing = this.parameters.filter(
      (parameter) => parameter.required && !Object.hasOwn(parameters, parameter.name),
    );
    if (missing.length > 0) {
      throw new TypeError(
        `Missing required parameter(s): ${missing.map(({ name }) => name).join(", ")}`,
      );
    }

    const args = this.parameters.map((parameter) =>
      Object.hasOwn(parameters, parameter.name) ? parameters[parameter.name] : parameter.default,
    );
    return Reflect.apply(this.method, this.parent, args) as ToolResult | Promise<ToolResult>;
  }
}
